# Generated by Django 4.1.5 on 2023-02-13 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefactor',
            name='experience',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0),
        ),
        migrations.AddField(
            model_name='benefactor',
            name='free_time_per_week',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='benefactor',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charity',
            name='name',
            field=models.CharField(default='Unnamed-Charity', max_length=50),
        ),
        migrations.AddField(
            model_name='charity',
            name='reg_number',
            field=models.CharField(default='-1', max_length=10),
        ),
        migrations.AddField(
            model_name='charity',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='age_limit_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='age_limit_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_benefactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charities.benefactor'),
        ),
        migrations.AddField(
            model_name='task',
            name='charity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='charities.charity'),
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='gender_limit',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('P', 'Pending'), ('W', 'Waiting'), ('A', 'Assigned'), ('D', 'Done')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Unknown-Title', max_length=60),
        ),
    ]
